---
name: pylsp
description: Hej
homepage: https://test.org
categories: []
languages: []
licenses:
  - MIT

source:
  id: pkg:pypi/@angular/angular-language-service[all]@nightly
bin:
  notabin: pypi:pylsp
